# Gunakan base image Python versi ringan
FROM python:3.11-slim

# Set direktori kerja di dalam container
WORKDIR /app

# Copy daftar dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy semua source code ke container
COPY . .

# Port aplikasi Flask
EXPOSE 5000

# Perintah untuk menjalankan server
CMD ["python", "app.py"]
